name: Auto commit

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "* * * * *" # See https://crontab.guru/#0_7,9,11_*_*_1,3

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "sajadrahimi0101@gmail.com"
          git config --local user.name "SajadRahimi1"
          git add -A
          
          arr[0]="Sajad 😂 auto commit"
          arr[1]="Sajad 😱 auto commit"
          arr[2]="Sajad 👿 auto commit"
          arr[3]="Sajad  auto commit"
          arr[4]="chore(bot): 🙏 auto commit"
          arr[5]="chore(bot): 🙈 auto commit"
          arr[6]="chore(bot): 🐐 auto commit"
          arr[7]="chore(bot): 🤖 auto commit"
          arr[8]="chore(bot): 🟩 auto commit"
          arr[9]="chore(bot): 👻 auto commit"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: "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"
